#==============================================================================
# CFA-GRM SIMULATION PIPELINE & METHODOLOGY FLOWCHART
#==============================================================================
# Manuscript  : Cognitive, Affective, and Conative Pathways in Human-GenAI
#               Interactions in Higher Education
# Article Type: Method Article
# R Version   : >= 4.6.1
#==============================================================================
# REPRODUCIBILITY
#   Seed       : 20260502
#   Sample size: N = 1,000 (Monte Carlo power analysis; Wolf et al., 2013)
#   All outputs are written to the project root directory.
#==============================================================================
# HOW TO RUN THIS SCRIPT
#
#   NORMAL RUN - this is the default. Takes 1-3 minutes.
#       source("ExtendedData_8_R_Analysis_Script.R")
#   Reproduces every figure and table in the main article (Figures 1-5,
#   Tables 1-4, Extended Data 1-7). Section 6 is skipped.
#
#   FULL RUN WITH THE MONTE CARLO REPLICATION STUDY - takes several hours.
#       RUN_MC <- TRUE; source("ExtendedData_8_R_Analysis_Script.R")
#   Adds Section 6, which produces Extended Data 9-11 (parameter recovery).
#   Do NOT edit this file to switch it on - just set RUN_MC in the console
#   first, as shown above. Progress is checkpointed to MC_raw_results_N*.rds
#   every 25 replications, so an interrupted run resumes where it stopped.
#
# VERIFYING THE RESULTS WITHOUT RERUNNING THE SIMULATION
#   You do not need to run Section 6 to check the reported recovery results.
#   The summary tables are deposited as ExtendedData_9/10/11.csv, and the
#   per-replication raw estimates as MC_raw_results_N1000.rds and
#   MC_raw_results_N300.rds. Place those two .rds files in the project root
#   and use the FULL RUN command above: the checkpoint is reused and the
#   tables are regenerated in under a minute, with no recomputation.
#   To recompute everything from scratch, delete the .rds files first.
#
# DO NOT CHANGE MC_REPS, MC_N, OR MC_SEED
#   These are stored inside the checkpoint files. If they differ, the
#   deposited results cannot be reused and the study restarts from zero.
#==============================================================================


# =============================================================================
# SECTION 0: ENVIRONMENT SETUP
# =============================================================================
if (!requireNamespace("pacman", quietly = TRUE)) {
  install.packages("pacman", repos = "https://cloud.r-project.org", quiet = TRUE)
}
pacman::p_load(
  lavaan, psych, MASS, dplyr, mirt, ggplot2,
  semTools, corrplot, tidyr, patchwork, stringr, here
)

# --- Constants ---------------------------------------------------------------
FIG_WIDTH_MM_MIN <- 75      # single-column lower bound
FIG_WIDTH_MM_MAX <- 150     # double-column upper bound
FIG_DPI_MIN      <- 600     # line-art minimum resolution
FIG_COMPRESSION  <- "none"  # uncompressed TIFF; set "lzw" (lossless) if the
                            # portal's file-size limit is exceeded
WRAP_WIDTH       <- 52      # character wrap width for Fig. 1 bullets
SEED             <- 20260502L

# One domain order and one color map for every figure
DOMAIN_LEVELS <- c("Cognitive", "Affective", "Conative")
DOMAIN_COLORS <- c(Cognitive = "#E74C3C", Affective = "#3498DB", Conative = "#27AE60")

# --- Manifest for compliance verification ------------------------------------
.fig_manifest <- data.frame(
  File = character(), Width_mm = numeric(),
  Height_mm = numeric(), DPI = numeric(),
  stringsAsFactors = FALSE
)

# --- Helper: write CSV with UTF-8 BOM (Excel-safe) ---------------------------
write_csv_utf8_bom <- function(data, filename) {
  con <- file(filename, "wb")
  writeBin(charToRaw("\xEF\xBB\xBF"), con)
  write.csv(data, con, row.names = FALSE)
  close(con)
  cat(sprintf("  [OK] %s saved (UTF-8 with BOM)\n", filename))
}

# --- Helper: numeric formatting (3 decimals; bounded p-values) --------------
fmt3  <- function(x) sprintf("%.3f", x)
fmt_p <- function(p) {
  if (is.na(p)) return(NA_character_)
  if (p > 0.999) return("> 0.999")
  if (p < 0.001) return("< 0.001")
  sprintf("%.3f", p)
}

# --- Helper: save figure as TIFF ---------------------------------------------
save_figure <- function(plot, filename, width, height, dpi = 600) {
  out <- paste0(tools::file_path_sans_ext(filename), ".tiff")
  tryCatch({
    ggsave(out, plot = plot, width = width, height = height,
           units = "cm", dpi = dpi, bg = "white",
           limitsize = FALSE, device = "tiff", compression = FIG_COMPRESSION)
    cat(sprintf("  [OK] %s saved (%.1f x %.1f cm, %d dpi, %s)\n",
                out, width, height, dpi, FIG_COMPRESSION))
    .fig_manifest[nrow(.fig_manifest) + 1, ] <<- list(
      File = out, Width_mm = width * 10, Height_mm = height * 10, DPI = dpi
    )
  }, error = function(e) {
    cat(sprintf("  [ERROR] Failed to save %s: %s\n", out, e$message))
  })
}


# =============================================================================
# SECTION 1: SYNTHETIC DATA GENERATION (GRM-BASED)
# =============================================================================
set.seed(SEED)
cat("\n=== [1/9] GENERATING N=1000 SYNTHETIC DATASET ===\n")

N <- 1000L; n_items <- 36L; n_cats <- 4L
items_per_factor <- 12L; n_factors <- 3L

idx_cog <- 1:items_per_factor
idx_aff <- (items_per_factor + 1):(2 * items_per_factor)
idx_con <- (2 * items_per_factor + 1):(3 * items_per_factor)
domain_idx   <- list(Cognitive = idx_cog, Affective = idx_aff, Conative = idx_con)
domain_names <- names(domain_idx)

# Latent correlation matrix (Cognitive-Affective-Conative trade-offs)
Phi <- matrix(0.35, n_factors, n_factors); diag(Phi) <- 1
Phi[1, 2] <- Phi[2, 1] <- 0.40
Phi[1, 3] <- Phi[3, 1] <- 0.35
Phi[2, 3] <- Phi[3, 2] <- 0.48

Theta <- MASS::mvrnorm(N, mu = rep(0, n_factors), Sigma = Phi)

# Item parameters: discrimination (a) and thresholds (b)
a_cog <- seq(1.3, 1.8, length.out = items_per_factor)
a_aff <- seq(0.9, 1.5, length.out = items_per_factor)
a_con <- seq(1.1, 1.7, length.out = items_per_factor)
a_params <- c(a_cog, a_aff, a_con)

b_base  <- matrix(rep(c(-1.2, 0.0, 1.1), n_items), nrow = n_items, byrow = TRUE)
b_noise <- matrix(rnorm(n_items * 3, mean = 0, sd = 0.10), n_items, 3)
b_params <- t(apply(b_base + b_noise, 1, sort))

data_sim <- matrix(NA_integer_, N, n_items)
for (i in 1:n_items) {
  a <- a_params[i]; b <- b_params[i, ]
  f_idx   <- ((i - 1) %/% items_per_factor) + 1
  theta_i <- Theta[, f_idx]
  p_ge2 <- 1 / (1 + exp(-a * (theta_i - b[1])))
  p_ge3 <- 1 / (1 + exp(-a * (theta_i - b[2])))
  p_ge4 <- 1 / (1 + exp(-a * (theta_i - b[3])))
  p1 <- 1 - p_ge2; p2 <- p_ge2 - p_ge3; p3 <- p_ge3 - p_ge4; p4 <- p_ge4
  probs <- cbind(p1, p2, p3, p4)
  probs[probs < 0 | is.na(probs)] <- 0
  probs <- probs / rowSums(probs)
  data_sim[, i] <- apply(probs, 1, function(p) sample(1:4, 1, prob = p))
}
data_sim <- as.data.frame(data_sim)
colnames(data_sim) <- paste0("It", 1:n_items)
for (j in 1:n_items) data_sim[[j]] <- factor(data_sim[[j]], levels = 1:4, ordered = TRUE)
cat("  [OK] Data generation complete.\n")


# =============================================================================
# SECTION 2: CONFIRMATORY FACTOR ANALYSIS (CFA)
# =============================================================================
cat("\n=== [2/9] ESTIMATING CFA MODEL (WLSMV) ===\n")

model_3F <- '
Cognitive =~ It1  + It2  + It3  + It4  + It5  + It6  + It7  + It8  + It9  + It10 + It11 + It12
Affective =~ It13 + It14 + It15 + It16 + It17 + It18 + It19 + It20 + It21 + It22 + It23 + It24
Conative  =~ It25 + It26 + It27 + It28 + It29 + It30 + It31 + It32 + It33 + It34 + It35 + It36
'
fit_3F <- lavaan::cfa(model_3F, data = data_sim, estimator = "WLSMV",
                      ordered = names(data_sim))

if (!lavaan::lavInspect(fit_3F, "converged")) {
  stop("[FATAL] CFA model did not converge.")
} else {
  cat("  [OK] CFA model converged.\n")
}
# Heywood check also covers improper standardized loadings
std_lambda <- lavaan::lavInspect(fit_3F, "std")$lambda
if (any(diag(lavaan::lavInspect(fit_3F, "cov.lv")) < 0) ||
    any(abs(std_lambda[std_lambda != 0]) >= 1)) {
  warning("[WARNING] Heywood case detected (negative latent variance or |std. loading| >= 1).")
}
cat("  [OK] CFA estimation complete.\n")


# =============================================================================
# SECTION 3: GRADED RESPONSE MODEL (GRM) CALIBRATION — PER DOMAIN
# =============================================================================
# GRM parameters and reliability are estimated separately for each 12-item
# domain, matching manuscript Section 2.4 ("a unidimensional IRT model for
# each domain"). This avoids attenuation from pooling three moderately
# correlated constructs (Phi = 0.35-0.48) into a single factor.
# =============================================================================
cat("\n=== [3/9] CALIBRATING GRM PARAMETERS AND RELIABILITY (PER DOMAIN) ===\n")

data_num <- as.data.frame(lapply(data_sim, as.numeric))

fit_grm_domain <- function(item_idx, label) {
  cat(sprintf("  Fitting GRM: %s domain (%d items)...\n", label, length(item_idx)))
  mirt::mirt(data_num[, item_idx], model = 1, itemtype = "graded", verbose = FALSE)
}
grm_fit_list <- lapply(domain_names, function(nm) fit_grm_domain(domain_idx[[nm]], nm))
names(grm_fit_list) <- domain_names

extract_irt_pars <- function(fit) {
  p <- coef(fit, IRTpars = TRUE, simplify = TRUE)$items
  list(a = p[, "a"], b = p[, c("b1", "b2", "b3"), drop = FALSE])
}
pars_by_domain <- lapply(grm_fit_list, extract_irt_pars)

a_vec <- unlist(lapply(domain_names, function(nm) pars_by_domain[[nm]]$a), use.names = FALSE)
b_mat <- do.call(rbind, lapply(domain_names, function(nm) pars_by_domain[[nm]]$b))

param_std <- lavaan::parameterEstimates(fit_3F, standardized = TRUE)
slf_df <- param_std %>% dplyr::filter(op == "=~") %>% dplyr::select(rhs, std.all)
colnames(slf_df) <- c("Item", "Loading")

cor_mat <- lavaan::lavInspect(fit_3F, "std")$psi

# Reliability per domain. Both coefficients are computed on the
# POLYCHORIC correlation matrix, so the alpha reported here is ORDINAL alpha
# (Zumbo et al., 2007), not Cronbach's alpha on raw item scores.
compute_domain_reliability <- function(item_idx, label) {
  poly   <- psych::polychoric(data_num[, item_idx])$rho
  a_val  <- tryCatch(psych::alpha(poly)$total$raw_alpha, error = function(e) NA_real_)
  om_val <- tryCatch(psych::omega(poly, nfactors = 1, plot = FALSE)$omega.tot,
                     error = function(e) NA_real_)
  cat(sprintf("  Reliability %s: ordinal alpha = %.3f | omega = %.3f\n", label, a_val, om_val))
  list(poly = poly, alpha = a_val, omega = om_val)
}
rel_by_domain   <- lapply(domain_names, function(nm) compute_domain_reliability(domain_idx[[nm]], nm))
names(rel_by_domain) <- domain_names
alpha_by_domain <- sapply(rel_by_domain, function(x) x$alpha)
omega_by_domain <- sapply(rel_by_domain, function(x) x$omega)

alpha_res <- mean(alpha_by_domain, na.rm = TRUE)
omega_res <- mean(omega_by_domain, na.rm = TRUE)
cat(sprintf("  [OK] Mean ordinal Alpha (3 domains): %.3f\n", alpha_res))
cat(sprintf("  [OK] Mean Omega (3 domains): %.3f\n", omega_res))


# =============================================================================
# SECTION 4: LATENT TYPOLOGY MAPPING
# =============================================================================
# classify_typology(): each label is assigned by explicit which.max/which.min
# comparison. "Balanced-Tripartite" requires the full range across all three
# scores to be below tol. "Conative-Deficit" requires Conative = argmin.
# Profiles not covered by the four theoretical typologies are labeled
# "Undifferentiated" rather than forced into an incorrect category.
# =============================================================================
cat("\n=== [4/9] GENERATING INTERACTION QUALITY PROFILES ===\n")

theta_cfa <- lavaan::lavPredict(fit_3F)
profiles <- data.frame(
  Respondent = 1:N,
  Cognitive  = theta_cfa[, "Cognitive"],
  Affective  = theta_cfa[, "Affective"],
  Conative   = theta_cfa[, "Conative"]
)

classify_typology <- function(cog, aff, con, tol = 0.3) {
  scores <- c(Cognitive = cog, Affective = aff, Conative = con)
  rng <- max(scores) - min(scores)
  if (rng < tol) return("Balanced-Tripartite")
  dominant  <- names(which.max(scores))
  deficient <- names(which.min(scores))
  if (dominant  == "Cognitive") return("Cognitive-Dominant")
  if (deficient == "Affective") return("Affective-Friction")
  if (deficient == "Conative")  return("Conative-Deficit")
  "Undifferentiated"
}

profiles$Typology <- mapply(classify_typology,
                            profiles$Cognitive,
                            profiles$Affective,
                            profiles$Conative)

n_undiff <- sum(profiles$Typology == "Undifferentiated")
cat(sprintf("  [INFO] %d/%d (%.1f%%) profiles labeled 'Undifferentiated'\n",
            n_undiff, N, 100 * n_undiff / N))

typology_table <- as.data.frame(table(profiles$Typology))
colnames(typology_table) <- c("Typology", "Count")
typology_table$Percentage <- round(typology_table$Count / sum(typology_table$Count) * 100, 1)

get_pct <- function(typo_name) {
  val <- typology_table$Percentage[typology_table$Typology == typo_name]
  if (length(val) == 0) 0 else val
}

profile_means <- profiles %>%
  tidyr::pivot_longer(cols = c(Cognitive, Affective, Conative),
                      names_to = "Domain", values_to = "Score") %>%
  dplyr::group_by(Typology, Domain) %>%
  dplyr::summarize(Score = mean(Score), .groups = "drop") %>%
  dplyr::mutate(Domain = factor(Domain, levels = DOMAIN_LEVELS))


# =============================================================================
# SECTION 5: EXPORT FILES IN NARRATIVE ORDER
# =============================================================================
cat("\n=== [5/9] EXPORTING FILES IN NARRATIVE ORDER ===\n")

# --- Extended Data 1: Simulation Specifications ------------------------------
cat("  -> [Extended] ExtendedData_1: Simulation Specifications\n")
add1_df <- data.frame(
  Parameter = c("Sample Size", "Total Items", "Items/Domain", "Scale",
                "Phi Range", "a Range", "b Range"),
  Value = c("1,000", "36", "12", "4-category ordinal scale",
            sprintf("%.2f-%.2f", 0.35, 0.48),
            sprintf("%.2f-%.2f", min(a_params), max(a_params)),
            sprintf("%.3f-%.3f", min(b_params), max(b_params))),
  check.names = FALSE
)
write_csv_utf8_bom(add1_df, "ExtendedData_1_Simulation_Specs.csv")

# --- Figure 1: Methodology Flowchart -----------------------------------------
cat("  -> [Main] Fig 1: Methodology Flowchart\n")

wrap_bullet <- function(text, width = WRAP_WIDTH) {
  paste(strwrap(paste0("- ", text), width = width, exdent = 2), collapse = "\n")
}
join_bullets <- function(bullets, width = WRAP_WIDTH) {
  paste(vapply(bullets, wrap_bullet, character(1), width = width), collapse = "\n")
}
fmt_r <- function(x) sub("^(-?)0\\.", "\\1.", sprintf("%.2f", x))

bullets_step1 <- c(
  "Monte Carlo simulation (N = 1,000)",
  "36 ordinal items across 3 latent domains",
  "4-pt ordinal scale for Higher Education",
  "Latent Phi: 0.35-0.48 (moderate dependency)"
)
bullets_step2 <- c(
  "WLSMV estimator for structural validity",
  "Scaled/robust fit: CFI, TLI, RMSEA, SRMR",
  "Ordinal alpha and omega per domain",
  "Ensures macro-pathway stability"
)
bullets_step3 <- c(
  "3 unidimensional GRMs (one per domain)",
  "Discrimination (a) and thresholds (b1-b3)",
  "ICC and Test Information Function per domain",
  "Calibrates domain-specific differentiation"
)
bullets_step4 <- c(
  "Latent scores via lavPredict (CFA)",
  "Inter-factor covariances for trade-offs",
  sprintf("Latent r: Cog-Aff = %s, Cog-Con = %s, Aff-Con = %s",
          fmt_r(cor_mat["Affective", "Cognitive"]),
          fmt_r(cor_mat["Conative",  "Cognitive"]),
          fmt_r(cor_mat["Conative",  "Affective"])),
  "Boundary: delegation vs. dependency"
)
bullets_step5 <- c(
  "Classifies profiles by interaction type",
  sprintf("Conative-Deficit (lowest confirmed): %.1f%%", get_pct("Conative-Deficit")),
  sprintf("Balanced-Tripartite: %.1f%%", get_pct("Balanced-Tripartite")),
  sprintf("Undifferentiated (outside typologies): %.1f%%", get_pct("Undifferentiated"))
)
bullets_step6 <- c(
  "Translates metrics into design protocols",
  "Warning trigger: affective items (a > 1.4)",
  "Adaptive scaffolding at domain peak-info theta",
  "Aligns with SDG 4.6/4.7 and human agency"
)

bullets_all <- list(bullets_step1, bullets_step2, bullets_step3,
                    bullets_step4, bullets_step5, bullets_step6)
detail_all  <- vapply(bullets_all, join_bullets, character(1))

count_lines <- function(text) length(strsplit(text, "\n", fixed = TRUE)[[1]])
n_lines <- vapply(detail_all, count_lines, integer(1))

LINE_PITCH   <- 0.60
FLOOR_CONST  <- 0.40
TITLE_HALF_H <- 1.4
BOX_GAP      <- 0.7
TOP_MARGIN   <- 0.8
BOT_MARGIN   <- 0.8

detail_half_h_uniform <- max(TITLE_HALF_H, FLOOR_CONST + max(n_lines) * LINE_PITCH / 2)
detail_half_h <- rep(detail_half_h_uniform, 6)

y_top_start <- 15.0
y_pos <- numeric(6)
y_cursor <- y_top_start
for (i in seq_len(6)) {
  y_pos[i] <- y_cursor - detail_half_h[i]
  y_cursor <- y_cursor - 2 * detail_half_h[i] - BOX_GAP
}
y_bottom_edge <- y_cursor + BOX_GAP
ylim_top    <- y_top_start + TOP_MARGIN
ylim_bottom <- y_bottom_edge - BOT_MARGIN

flow_data <- data.frame(
  step  = 1:6,
  title = c("1. Data\nGeneration", "2. CFA\nValidation", "3. GRM\nCalibration",
            "4. Latent\nExtraction", "5. Typology\nMapping",
            "6. Evidence-Based\nInteraction Design"),
  detail = detail_all,
  y_pos  = y_pos,
  detail_half_h = detail_half_h,
  stringsAsFactors = FALSE
)

arrow_data <- data.frame(
  x       = 3.35,
  y_start = y_pos[1:5] - TITLE_HALF_H,
  y_end   = y_pos[2:6] + TITLE_HALF_H
)

p_flow <- ggplot2::ggplot() +
  ggplot2::geom_segment(data = arrow_data,
                        ggplot2::aes(x = x, y = y_start, xend = x, yend = y_end),
                        arrow = grid::arrow(length = grid::unit(0.35, "cm"),
                                            type = "closed", ends = "last"),
                        color = "#475569", linewidth = 1.2) +
  ggplot2::geom_segment(data = flow_data,
                        ggplot2::aes(x = 6.2, y = y_pos, xend = 6.8, yend = y_pos),
                        color = "#475569", linewidth = 1.0) +
  ggplot2::geom_rect(data = flow_data,
                     ggplot2::aes(xmin = 0.5, xmax = 6.2,
                                  ymin = y_pos - TITLE_HALF_H,
                                  ymax = y_pos + TITLE_HALF_H),
                     fill = "#1E3A8A", color = "#1E3A8A", linewidth = 0.5) +
  ggplot2::geom_rect(data = flow_data,
                     ggplot2::aes(xmin = 6.8, xmax = 18.2,
                                  ymin = y_pos - detail_half_h,
                                  ymax = y_pos + detail_half_h),
                     fill = "#F8FAFC", color = "#CBD5E1", linewidth = 0.8) +
  ggplot2::geom_text(data = flow_data,
                     ggplot2::aes(x = 3.35, y = y_pos, label = title),
                     size = 3.8, fontface = "bold", family = "sans",
                     color = "white", lineheight = 1.1) +
  ggplot2::geom_text(data = flow_data,
                     ggplot2::aes(x = 7.2, y = y_pos, label = detail),
                     size = 3.0, family = "sans", color = "#334155",
                     hjust = 0, vjust = 0.5, lineheight = 1.2) +
  ggplot2::coord_fixed(xlim = c(0, 19.0), ylim = c(ylim_bottom, ylim_top)) +
  ggplot2::theme_void() +
  ggplot2::theme(plot.background = ggplot2::element_rect(fill = "white", color = NA),
                 plot.margin = ggplot2::margin(10, 10, 10, 10))

fig1_scale_mm_per_unit <- FIG_WIDTH_MM_MAX / 19
fig1_height_cm <- (ylim_top - ylim_bottom) * fig1_scale_mm_per_unit / 10
cat(sprintf("  [INFO] Fig 1: computed height = %.1f cm (uniform boxes, max %d lines/step)\n",
            fig1_height_cm, max(n_lines)))

save_figure(p_flow, "Fig1_Methodology_Flowchart.tiff",
            width = FIG_WIDTH_MM_MAX / 10, height = fig1_height_cm)

# --- Underlying Data 1: Raw Simulated Dataset --------------------------------
cat("  -> [Underlying] UnderlyingData_1: Simulated Dataset N=1000\n")
write_csv_utf8_bom(data_sim, "UnderlyingData_1_Dataset_Simulated_N1000.csv")

# --- Table 1: CFA Fit Indices ------------------------------------------------
cat("  -> [Main] Table 1: CFA Fit Indices\n")
# With estimator = "WLSMV", fitMeasures(fit, "chisq") is the UNSCALED
# DWLS statistic, and "cfi"/"tli"/"rmsea" are the naive indices built on it.
# The correct test is the scaled (mean- and variance-adjusted) chi-square;
# CFI/TLI/RMSEA are taken from the robust versions, falling back to the
# scaled versions if the installed lavaan does not provide robust indices
# for categorical data. Names are looked up safely across lavaan versions.
fm_all <- lavaan::fitMeasures(fit_3F)
fm_get <- function(name) {
  if (name %in% names(fm_all)) unname(as.numeric(fm_all[[name]])) else NA_real_
}
# One index family for all of CFI/TLI/RMSEA (never a robust/scaled mix)
fit_idx <- c("cfi", "tli", "rmsea", "rmsea.ci.lower", "rmsea.ci.upper")
fit_sfx <- if (all(!is.na(vapply(paste0(fit_idx, ".robust"), fm_get, numeric(1))))) {
  "robust"
} else {
  "scaled"
}
fit_rep <- list(
  chisq    = fm_get("chisq.scaled"),
  df       = fm_get("df.scaled"),
  pvalue   = fm_get("pvalue.scaled"),
  cfi      = fm_get(paste0("cfi.", fit_sfx)),
  tli      = fm_get(paste0("tli.", fit_sfx)),
  rmsea    = fm_get(paste0("rmsea.", fit_sfx)),
  rmsea_lo = fm_get(paste0("rmsea.ci.lower.", fit_sfx)),
  rmsea_hi = fm_get(paste0("rmsea.ci.upper.", fit_sfx)),
  srmr     = fm_get("srmr"),
  type     = fit_sfx
)
if (is.na(fit_rep$chisq)) stop("[FATAL] Scaled chi-square not found in fitMeasures().")
cat(sprintf("  [INFO] Fit indices reported: %s | scaled chi-square = %.2f, df = %.0f, p = %s\n",
            fit_rep$type, fit_rep$chisq, fit_rep$df, fmt_p(fit_rep$pvalue)))

table1_df <- data.frame(
  Model          = "3-Factor Tripartite (C-A-C)",
  CFI            = fmt3(fit_rep$cfi),
  TLI            = fmt3(fit_rep$tli),
  RMSEA          = fmt3(fit_rep$rmsea),
  `RMSEA 90% CI` = sprintf("[%s, %s]", fmt3(fit_rep$rmsea_lo), fmt3(fit_rep$rmsea_hi)),
  SRMR           = fmt3(fit_rep$srmr),
  ChiSq_scaled   = sprintf("%.2f", fit_rep$chisq),
  df             = sprintf("%.0f", fit_rep$df),
  p_value        = fmt_p(fit_rep$pvalue),
  Index_type     = fit_rep$type,
  check.names    = FALSE
)
write_csv_utf8_bom(table1_df, "UnderlyingData_2_Table1_CFA_Fit_Indices.csv")

# --- Figure 2: Panel Correlation + TIF ---------------------------------------
cat("  -> [Main] Fig 2: Panel Correlation + TIF\n")
theta_range <- seq(-4, 4, by = 0.1)
tif_by_domain <- lapply(domain_names, function(nm) {
  mirt::testinfo(grm_fit_list[[nm]], theta_range)
})
names(tif_by_domain) <- domain_names

tif_df <- data.frame(
  Theta  = rep(theta_range, times = length(domain_names)),
  Info   = unlist(tif_by_domain, use.names = FALSE),
  Domain = factor(rep(domain_names, each = length(theta_range)), levels = DOMAIN_LEVELS)
)
peak_df <- data.frame(
  Domain = factor(domain_names, levels = DOMAIN_LEVELS),
  Theta  = sapply(domain_names, function(nm) theta_range[which.max(tif_by_domain[[nm]])]),
  Info   = sapply(domain_names, function(nm) max(tif_by_domain[[nm]]))
)

cor_mat_df <- as.data.frame(as.table(cor_mat))
colnames(cor_mat_df) <- c("Var1", "Var2", "Corr")
# A diagonal value a hair above 1 (floating-point, e.g. 1 + 1e-15)
# fell outside limits = c(0, 1) and was drawn as a grey NA cell. Values are
# rounded, and oob = scales::squish keeps anything out of range on the scale.
cor_mat_df$Var1 <- factor(cor_mat_df$Var1, levels = DOMAIN_LEVELS)
cor_mat_df$Var2 <- factor(cor_mat_df$Var2, levels = DOMAIN_LEVELS)
cor_mat_df$Corr <- round(as.numeric(cor_mat_df$Corr), 10)

p_corr_gg <- ggplot2::ggplot(cor_mat_df, ggplot2::aes(x = Var1, y = Var2, fill = Corr)) +
  ggplot2::geom_tile(color = "white", linewidth = 1) +
  ggplot2::geom_text(ggplot2::aes(label = sprintf("%.2f", Corr)), size = 5) +
  ggplot2::scale_fill_gradient2(low = "white", high = "#2C3E50", mid = "#A9CCE3",
                                midpoint = 0.4, limits = c(0, 1), name = "Corr",
                                oob = scales::squish) +
  ggplot2::labs(x = NULL, y = NULL) +                        # no "Var1/Var2"
  ggplot2::theme_minimal(base_size = 11) +
  ggplot2::theme(legend.position = "bottom",
                 axis.text.x = ggplot2::element_text(angle = 45, hjust = 1),
                 panel.grid = ggplot2::element_blank(),
                 text = ggplot2::element_text(family = "sans"))

p_tif_gg <- ggplot2::ggplot(tif_df, ggplot2::aes(x = Theta, y = Info, color = Domain)) +
  ggplot2::geom_line(linewidth = 1.1) +
  ggplot2::geom_point(data = peak_df, size = 2.4, show.legend = FALSE) +
  ggplot2::scale_color_manual(values = DOMAIN_COLORS) +
  ggplot2::labs(x = "Latent Trait (theta)", y = "Test Information") +
  ggplot2::theme_minimal(base_size = 11) +
  ggplot2::theme(legend.position = "bottom",
                 text = ggplot2::element_text(family = "sans"))

p_panel_corr_tif <- p_tif_gg + p_corr_gg +
  patchwork::plot_annotation(tag_levels = "A") &
  ggplot2::theme(legend.position = "bottom")

save_figure(p_panel_corr_tif, "Fig2_Panel_Correlation_TIF.tiff",
            width = FIG_WIDTH_MM_MAX / 10, height = 8.5)

# --- Table 2: GRM Parameter Summary by Domain --------------------------------
cat("  -> [Main] Table 2: GRM Parameter Summary by Domain\n")
# fmt3() keeps trailing zeros (e.g., "1.560", not "1.56") so every value
# really has 3 decimals. The alpha column is labeled "Ordinal Alpha".
tbl2_summary <- data.frame(
  Domain = c("Cognitive", "Affective", "Conative"),
  `n Items` = 12,
  `Mean Loading (SD)` = paste0(
    fmt3(c(mean(slf_df$Loading[idx_cog]),
           mean(slf_df$Loading[idx_aff]),
           mean(slf_df$Loading[idx_con]))),
    " (",
    fmt3(c(sd(slf_df$Loading[idx_cog]),
           sd(slf_df$Loading[idx_aff]),
           sd(slf_df$Loading[idx_con]))), ")"),
  `Mean Discrimination (SD)` = paste0(
    fmt3(c(mean(a_vec[idx_cog]), mean(a_vec[idx_aff]), mean(a_vec[idx_con]))),
    " (",
    fmt3(c(sd(a_vec[idx_cog]), sd(a_vec[idx_aff]), sd(a_vec[idx_con]))), ")"),
  `Mean Thresholds (b1, b2, b3)` = paste0(
    fmt3(c(mean(b_mat[idx_cog, 1]), mean(b_mat[idx_aff, 1]), mean(b_mat[idx_con, 1]))), ", ",
    fmt3(c(mean(b_mat[idx_cog, 2]), mean(b_mat[idx_aff, 2]), mean(b_mat[idx_con, 2]))), ", ",
    fmt3(c(mean(b_mat[idx_cog, 3]), mean(b_mat[idx_aff, 3]), mean(b_mat[idx_con, 3])))),
  `Ordinal Alpha (domain)` = fmt3(alpha_by_domain),
  `Omega (domain)` = fmt3(omega_by_domain),
  check.names = FALSE
)
write_csv_utf8_bom(tbl2_summary, "UnderlyingData_3_Table2_GRM_Summary.csv")

# --- Extended Data 2: Full GRM Parameters ------------------------------------
cat("  -> [Extended] ExtendedData_2: Full GRM Parameters (36 items)\n")
full_grm <- data.frame(
  Item           = slf_df$Item,
  Domain         = rep(c("Cognitive", "Affective", "Conative"), each = 12),
  Loading        = round(slf_df$Loading, 3),
  Discrimination = round(a_vec, 3),
  b1             = round(b_mat[, 1], 3),
  b2             = round(b_mat[, 2], 3),
  b3             = round(b_mat[, 3], 3),
  check.names    = FALSE
)
write_csv_utf8_bom(full_grm, "ExtendedData_2_FullGRM_Parameters.csv")

# --- Figure 3: Panel Threshold + ICC -----------------------------------------
cat("  -> [Main] Fig 3: Panel Threshold + ICC\n")
# as.vector(t(b_mat)) is ordered item by item (It1 b1-b3, It2 b1-b3, ...;
# 108 values), so each item's own domain must be repeated once per threshold.
# A 36-element Domain vector would be silently recycled against 108 values and
# every box would mix items from all three domains.
df_thresh_pan <- data.frame(
  Domain    = factor(rep(rep(DOMAIN_LEVELS, each = items_per_factor), each = n_cats - 1),
                     levels = DOMAIN_LEVELS),
  Threshold = rep(c("b1", "b2", "b3"), times = n_items),
  Value     = as.vector(t(b_mat)),
  check.names = FALSE
)
stopifnot(nrow(df_thresh_pan) == n_items * (n_cats - 1))

# Category response curves are taken from the fitted GRMs with
# mirt::probtrace(), which returns P(X = k) directly. Writing the curves by
# hand from the logistic thresholds risks drawing "Cat 1" as P(X >= 2), a
# rising curve, rather than P(X = 1) = 1 - P(X >= 2).
icc_items <- data.frame(global = c(1, 13, 25), domain = DOMAIN_LEVELS,
                        local = 1, stringsAsFactors = FALSE)
th_grid <- seq(-4, 4, 0.1)
df_icc <- do.call(rbind, lapply(seq_len(nrow(icc_items)), function(r) {
  item_obj <- mirt::extract.item(grm_fit_list[[icc_items$domain[r]]], icc_items$local[r])
  P <- mirt::probtrace(item_obj, matrix(th_grid))
  stopifnot(ncol(P) == n_cats, all(abs(rowSums(P) - 1) < 1e-8))
  data.frame(Theta    = rep(th_grid, times = n_cats),
             Prob     = as.vector(P),
             Category = rep(paste("Cat", seq_len(n_cats)), each = length(th_grid)),
             Item     = paste0("Item ", icc_items$global[r], "\n(", icc_items$domain[r], ")"),
             check.names = FALSE)
}))
df_icc$Item <- factor(df_icc$Item, levels = unique(df_icc$Item))

p_thresh_pan <- ggplot2::ggplot(df_thresh_pan,
                                ggplot2::aes(x = Domain, y = Value, fill = Threshold)) +
  # outliers hidden in the boxplot because every point is already
  # drawn by the jitter layer (they were plotted twice); jitter is now
  # horizontal only (threshold values are not shifted) and seeded.
  ggplot2::geom_boxplot(alpha = 0.7, width = 0.5, outlier.shape = NA) +
  ggplot2::geom_point(position = ggplot2::position_jitter(width = 0.15, height = 0,
                                                          seed = SEED),
                      size = 1.5, alpha = 0.8, color = "#2C3E50") +
  ggplot2::geom_hline(yintercept = 0, linetype = "dashed",
                      color = "black", linewidth = 0.7) +
  ggplot2::scale_fill_manual(values = c("b1" = "#E8B4B8",
                                        "b2" = "#A8C5D6",
                                        "b3" = "#B5C9A5")) +
  ggplot2::labs(x = "Domain", y = "Logit Scale") +
  ggplot2::theme_minimal(base_size = 11) +
  ggplot2::theme(legend.position = "bottom",
                 plot.margin = ggplot2::margin(10, 5, 0, 10),
                 text = ggplot2::element_text(family = "sans"))

p_icc_pan <- ggplot2::ggplot(df_icc,
                             ggplot2::aes(x = Theta, y = Prob,
                                          color = Category, linetype = Category)) +
  ggplot2::geom_line(linewidth = 1.0) +
  ggplot2::facet_wrap(~ Item, ncol = 3) +
  ggplot2::scale_color_manual(values = c("#D90000", "#0055A4", "#009933", "#9933CC")) +
  ggplot2::scale_linetype_manual(values = c("Cat 1" = "solid",
                                            "Cat 2" = "dashed",
                                            "Cat 3" = "dashed",
                                            "Cat 4" = "dashed")) +
  ggplot2::labs(x = "Latent Trait (theta)", y = "Probability") +
  ggplot2::theme_minimal(base_size = 11) +
  ggplot2::theme(legend.position = "bottom",
                 plot.margin = ggplot2::margin(10, 20, 15, 10),
                 strip.text = ggplot2::element_text(size = 10,
                                                    margin = ggplot2::margin(b = 5)),
                 legend.box.margin = ggplot2::margin(-5, 0, 0, 0),
                 text = ggplot2::element_text(family = "sans"))

p_combined_fig3 <- (p_thresh_pan + p_icc_pan +
                      patchwork::plot_layout(widths = c(1, 1.3), guides = "collect")) +
  patchwork::plot_annotation(tag_levels = "A") &
  ggplot2::theme(legend.position = "bottom",
                 legend.box = "vertical",
                 legend.box.just = "center",
                 legend.margin = ggplot2::margin(t = 2, b = 2))

save_figure(p_combined_fig3, "Fig3_Panel_Threshold_ICC.tiff",
            width = FIG_WIDTH_MM_MAX / 10, height = 12.5)

# Figure numbering follows the manuscript (Section 3.3 and the figure
# legends): Figure 4 = typology distribution (bar chart), Figure 5 = mean
# latent profiles (line chart). A working folder that also contains files
# under the opposite numbering would deposit two competing versions of each
# figure, so they are flagged here as a housekeeping guard.
stale_fig45 <- c("Fig4_Interaction_Profiles.tiff", "Fig5_Typology_Distribution.tiff")
if (any(file.exists(stale_fig45))) {
  cat(sprintf("  [INFO] Files using the opposite Fig 4 / Fig 5 numbering found: %s\n",
              paste(stale_fig45[file.exists(stale_fig45)], collapse = ", ")))
  cat("         Delete them before depositing so they are not mistaken for Fig 4 / Fig 5.\n")
}

# --- Figure 4: Typology Distribution -----------------------------------------
cat("  -> [Main] Fig 4: Typology Distribution\n")
typo_colors <- c("Affective-Friction"  = "#F87667",
                 "Balanced-Tripartite" = "#7CAE00",
                 "Cognitive-Dominant"  = "#00BFC4",
                 "Conative-Deficit"    = "#C77CFF",
                 "Undifferentiated"    = "#999999")

p_typo_bar <- ggplot2::ggplot(typology_table,
                              ggplot2::aes(x = reorder(Typology, Count),
                                           y = Count, fill = Typology)) +
  ggplot2::geom_col(width = 0.75) +
  ggplot2::geom_text(ggplot2::aes(label = paste0(Count, "\n(", Percentage, "%)")),
                     position = position_stack(vjust = 0.5),
                     size = 2.9, fontface = "bold", color = "#1A252F") +
  ggplot2::labs(x = NULL, y = "Frequency") +
  ggplot2::theme_minimal() +
  ggplot2::scale_fill_manual(values = typo_colors) +
  ggplot2::theme(legend.position = "right",
                 legend.title = ggplot2::element_text(size = 11, face = "bold"),
                 legend.text  = ggplot2::element_text(size = 9.5),
                 axis.text.x  = ggplot2::element_blank(),
                 axis.ticks.x = ggplot2::element_blank(),
                 axis.title.x = ggplot2::element_blank(),
                 panel.grid.minor = ggplot2::element_blank(),
                 text = ggplot2::element_text(family = "sans"))

save_figure(p_typo_bar, "Fig4_Typology_Distribution.tiff",
            width = 14, height = 7.2)

# --- Figure 5: Interaction Quality Profiles ----------------------------------
cat("  -> [Main] Fig 5: Interaction Quality Profiles\n")
p_profile <- ggplot2::ggplot(profile_means,
                             ggplot2::aes(x = Domain, y = Score,
                                          group = Typology, color = Typology)) +
  ggplot2::geom_line(linewidth = 1.2) +
  ggplot2::geom_point(size = 4) +
  ggplot2::labs(x = "Interaction Pathway", y = "Mean Latent Score") +
  ggplot2::theme_minimal(base_size = 12) +
  ggplot2::scale_color_brewer(palette = "Dark2") +
  ggplot2::theme(legend.position = "right",
                 text = ggplot2::element_text(family = "sans"))

save_figure(p_profile, "Fig5_Interaction_Profiles.tiff",
            width = 14.0, height = 6.5)

# --- Table 3: Latent Typologies & Pedagogical Implications -------------------
cat("  -> [Main] Table 3: Latent Typologies & Pedagogical Implications\n")
typology_chars <- profiles %>%
  dplyr::group_by(Typology) %>%
  dplyr::summarize(
    n          = dplyr::n(),
    Percentage = round(n / N * 100, 1),
    `Cog Mean` = round(mean(Cognitive), 3),
    `Aff Mean` = round(mean(Affective), 3),
    `Con Mean` = round(mean(Conative), 3),
    .groups = "drop"
  ) %>%
  dplyr::mutate(
    `Latent Characteristics` = dplyr::case_when(
      Typology == "Affective-Friction"  ~ sprintf("Aff < Cog, Con (~%.3f)", `Aff Mean`),
      Typology == "Balanced-Tripartite" ~ sprintf("Cog = Aff = Con (~%.3f)", `Cog Mean`),
      Typology == "Cognitive-Dominant"  ~ sprintf("Cog > Aff, Con (~%.3f)", `Cog Mean`),
      Typology == "Conative-Deficit"    ~ sprintf("Con lowest (Cog = %.3f, Aff = %.3f, Con = %.3f)",
                                                  `Cog Mean`, `Aff Mean`, `Con Mean`),
      Typology == "Undifferentiated"    ~ sprintf("Outside the 4 theoretical typologies (Cog = %.3f, Aff = %.3f, Con = %.3f)",
                                                  `Cog Mean`, `Aff Mean`, `Con Mean`),
      TRUE ~ NA_character_
    ),
    `Scaffolding Implications` = dplyr::case_when(
      Typology == "Affective-Friction"  ~ "High emotional friction. Needs trust calibration and anxiety reduction.",
      Typology == "Balanced-Tripartite" ~ "Ideal profile. Full GenAI access with reflective monitoring.",
      Typology == "Cognitive-Dominant"  ~ "Strong critical evaluation; risk of over-reliance. Requires conative scaffolding.",
      Typology == "Conative-Deficit"    ~ "Low self-regulation (Conative pathway confirmed lowest). Requires goal-setting and regulated AI use training.",
      Typology == "Undifferentiated"    ~ "Does not fit the 4 main theoretical typologies; needs further review before recommendations are assigned.",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(Typology, n, Percentage, `Latent Characteristics`, `Scaffolding Implications`)

typology_order <- c("Affective-Friction", "Balanced-Tripartite", "Cognitive-Dominant",
                    "Conative-Deficit", "Undifferentiated")
typology_chars$Typology <- factor(typology_chars$Typology, levels = typology_order)
typology_chars <- typology_chars[order(typology_chars$Typology), ]

write_csv_utf8_bom(typology_chars, "UnderlyingData_4_Table3_Latent_Typologies.csv")

# --- Extended Data 3: Individual Typologies ----------------------------------
cat("  -> [Extended] ExtendedData_3: Individual Typologies (N=1000)\n")
profiles_fixed <- profiles %>%
  dplyr::mutate(Cognitive = round(Cognitive, 3),
                Affective = round(Affective, 3),
                Conative  = round(Conative, 3))
write_csv_utf8_bom(profiles_fixed, "ExtendedData_3_Individual_Typologies_N1000.csv")

# --- Extended Data 4: Fig S1 Latent Trait Distribution -----------------------
cat("  -> [Extended] ExtendedData_4: Fig S1 - Latent Trait Distribution\n")
theta_long <- as.data.frame(theta_cfa) %>%
  tidyr::pivot_longer(cols = c("Cognitive", "Affective", "Conative"),
                      names_to = "Domain", values_to = "Score") %>%
  dplyr::mutate(Domain = factor(Domain, levels = DOMAIN_LEVELS))

p_dist <- ggplot2::ggplot(theta_long, ggplot2::aes(x = Score, fill = Domain)) +
  ggplot2::geom_histogram(alpha = 0.6, bins = 30, position = "identity") +
  ggplot2::facet_wrap(~ Domain, ncol = 1) +
  ggplot2::scale_fill_manual(values = DOMAIN_COLORS) +
  ggplot2::labs(x = "Latent score (CFA factor score)", y = "Count") +
  ggplot2::theme_minimal() +
  ggplot2::theme(legend.position = "none",
                 text = ggplot2::element_text(family = "sans"))

save_figure(p_dist, "ExtendedData_4_FigS1_Latent_Trait_Distribution.tiff",
            width = 8.5, height = 7.8)

# --- Table 4: Domain Design Implications -------------------------------------
cat("  -> [Main] Table 4: Domain Design Implications\n")
peak_theta <- setNames(peak_df$Theta, as.character(peak_df$Domain))

table4_main <- data.frame(
  Domain = c("Cognitive", "Affective", "Conative"),
  `Mean Discrimination` = fmt3(c(mean(a_vec[idx_cog]),
                                 mean(a_vec[idx_aff]),
                                 mean(a_vec[idx_con]))),
  `Peak Information Theta` = fmt3(peak_theta[c("Cognitive", "Affective", "Conative")]),
  `Design Implication` = c(
    "High precision. Scaffold complex problem-solving at theta > 0.5.",
    "Discrimination > 1.4 = early emotional friction. Implement empathy-calibrated feedback.",
    "Low thresholds = rapid reliance onset. Require self-regulation scaffolding first."
  ),
  `Actionable Scaffolding Strategy` = c(
    "Adaptive Challenge Laddering: escalate difficulty only after student demonstrates critical evaluation of prior AI output.",
    "Affective Pause Protocol: pause and offer validation when friction signals (e.g., repeated prompts) are detected.",
    "Pre-Access Goal Contract: require goal-setting and self-verification plan before full AI access."
  ),
  check.names = FALSE
)
write_csv_utf8_bom(table4_main, "UnderlyingData_5_Table4_Domain_Design.csv")

# --- Extended Data 5: Fig S2 Item Information Functions ----------------------
cat("  -> [Extended] ExtendedData_5: Fig S2 - Item Information Functions\n")
# Item information comes from mirt::iteminfo() on the fitted per-domain GRMs
# (same representative items as Fig 3B), which is the Samejima GRM item
# information. Summing a^2 * P*(1 - P*) over the three category boundaries is
# NOT that quantity: it overstates information roughly twofold and does not
# add up to the test information function in Fig 2A. The check below confirms
# that the item curves sum to the TIF.
iif_data <- do.call(rbind, lapply(seq_len(nrow(icc_items)), function(r) {
  item_obj <- mirt::extract.item(grm_fit_list[[icc_items$domain[r]]], icc_items$local[r])
  data.frame(Theta  = theta_range,
             Info   = mirt::iteminfo(item_obj, matrix(theta_range)),
             Item   = paste0("Item ", icc_items$global[r], "\n(", icc_items$domain[r], ")"),
             Domain = icc_items$domain[r],
             check.names = FALSE)
}))
iif_data$Item   <- factor(iif_data$Item, levels = unique(iif_data$Item))
iif_data$Domain <- factor(iif_data$Domain, levels = DOMAIN_LEVELS)

# Check: within each domain, item information must sum to the TIF (Fig 2A)
iif_tif_gap <- sapply(domain_names, function(nm) {
  sum_iif <- Reduce(`+`, lapply(seq_len(items_per_factor), function(j) {
    mirt::iteminfo(mirt::extract.item(grm_fit_list[[nm]], j), matrix(theta_range))
  }))
  max(abs(sum_iif - tif_by_domain[[nm]]))
})
if (all(iif_tif_gap < 1e-6)) {
  cat("  [OK] Item information sums to each domain's TIF (Fig 2A).\n")
} else {
  warning(sprintf("[WARNING] Item information does not sum to the TIF (max gap = %.2e).",
                  max(iif_tif_gap)))
}

p_iif <- ggplot2::ggplot(iif_data, ggplot2::aes(x = Theta, y = Info, color = Domain)) +
  ggplot2::geom_line(linewidth = 1.0) +
  ggplot2::facet_wrap(~ Item, ncol = 3) +
  ggplot2::scale_color_manual(values = DOMAIN_COLORS) +
  ggplot2::labs(x = "Latent Trait (theta)", y = "Item Information") +
  ggplot2::theme_minimal() +
  ggplot2::theme(legend.position = "none",
                 text = ggplot2::element_text(family = "sans"))

save_figure(p_iif, "ExtendedData_5_FigS2_Item_Information_Functions.tiff",
            width = FIG_WIDTH_MM_MAX / 10, height = 6)

# --- Extended Data 6: Fig S3 Reliability by Domain ---------------------------
cat("  -> [Extended] ExtendedData_6: Fig S3 - Reliability by Domain\n")
omega_data <- data.frame(
  Domain = factor(rep(domain_names, times = 2), levels = DOMAIN_LEVELS),
  # relabeled; factor levels keep alpha as the left/first (red) bar
  Metric = factor(rep(c("Ordinal alpha", "McDonald's omega"), each = length(domain_names)),
                  levels = c("Ordinal alpha", "McDonald's omega")),
  Value  = c(alpha_by_domain[domain_names], omega_by_domain[domain_names]),
  check.names = FALSE
)

p_omega <- ggplot2::ggplot(omega_data, ggplot2::aes(x = Domain, y = Value, fill = Metric)) +
  ggplot2::geom_col(position = position_dodge(width = 0.7), width = 0.6) +
  ggplot2::geom_text(ggplot2::aes(label = sprintf("%.3f", Value)),
                     position = position_dodge(width = 0.7),
                     vjust = -0.5, size = 3.6, fontface = "bold", color = "#2C3E50") +
  ggplot2::geom_hline(yintercept = 0.70, linetype = "dashed",
                      color = "#E74C3C", linewidth = 1) +
  ggplot2::annotate("text", x = 0.6, y = 0.74, label = "0.70",
                    size = 3.2, color = "black", fontface = "bold", hjust = 0) +
  ggplot2::ylim(0, max(omega_data$Value, na.rm = TRUE) + 0.08) +
  ggplot2::labs(x = NULL, y = "Reliability Coefficient") +
  ggplot2::theme_minimal(base_size = 11) +
  ggplot2::theme(legend.position = "bottom",
                 legend.title = ggplot2::element_blank(),
                 text = ggplot2::element_text(family = "sans"),
                 panel.grid.minor = ggplot2::element_blank())

save_figure(p_omega, "ExtendedData_6_FigS3_Omega_Reliability.tiff",
            width = 12, height = 7.5)

# --- Extended Data 7: Model Estimation Summary -------------------------------
cat("  -> [Extended] ExtendedData_7: Model Estimation Summary\n")
# Same scaled/robust statistics as Table 1; the unscaled DWLS
# chi-square is listed last for reference only.
fit_indices <- data.frame(
  Metric = c("Estimator", "Fit index type",
             "Chi-square (scaled)", "df", "p-value (scaled)",
             "CFI", "TLI", "RMSEA", "RMSEA CI Low", "RMSEA CI High", "SRMR",
             "Chi-square (unscaled DWLS; reference only)", "df (unscaled)"),
  Value = c("WLSMV", fit_rep$type,
            sprintf("%.2f", fit_rep$chisq),
            sprintf("%.0f", fit_rep$df),
            fmt_p(fit_rep$pvalue),
            fmt3(fit_rep$cfi),
            fmt3(fit_rep$tli),
            fmt3(fit_rep$rmsea),
            fmt3(fit_rep$rmsea_lo),
            fmt3(fit_rep$rmsea_hi),
            fmt3(fit_rep$srmr),
            sprintf("%.2f", fm_get("chisq")),
            sprintf("%.0f", fm_get("df"))),
  check.names = FALSE
)

reliability_summary <- data.frame(
  Metric = c("Ordinal Alpha - Cognitive", "Ordinal Alpha - Affective",
             "Ordinal Alpha - Conative",
             "Omega - Cognitive", "Omega - Affective", "Omega - Conative"),
  Value = sprintf("%.3f", c(alpha_by_domain["Cognitive"],
                            alpha_by_domain["Affective"],
                            alpha_by_domain["Conative"],
                            omega_by_domain["Cognitive"],
                            omega_by_domain["Affective"],
                            omega_by_domain["Conative"])),
  check.names = FALSE
)

grm_summary <- data.frame(
  Metric = c("GRM Discrimination Mean (Cog/Aff/Con)",
             "GRM Threshold Means, all 36 items (b1|b2|b3)",
             "Peak Information Theta (Cog/Aff/Con)"),
  Value = c(sprintf("%.3f / %.3f / %.3f",
                    mean(a_vec[idx_cog]), mean(a_vec[idx_aff]), mean(a_vec[idx_con])),
            sprintf("b1: %.3f | b2: %.3f | b3: %.3f",
                    mean(b_mat[, 1]), mean(b_mat[, 2]), mean(b_mat[, 3])),
            sprintf("%.3f / %.3f / %.3f",
                    peak_theta["Cognitive"], peak_theta["Affective"], peak_theta["Conative"])),
  check.names = FALSE
)

model_summary <- rbind(fit_indices, reliability_summary, grm_summary)
write_csv_utf8_bom(model_summary, "ExtendedData_7_Model_Estimation_Summary.csv")


# =============================================================================
# SECTION 6: MONTE CARLO REPLICATION STUDY (PARAMETER RECOVERY)
# =============================================================================
# Sections 1-5 analyse ONE simulated dataset. This section repeats
# generate -> CFA -> GRM MC_REPS times for each sample size in MC_N. The TRUE
# population parameters stay fixed (Phi, a_params, b_params from Section 1);
# only the latent traits and the item responses are redrawn.
#
# Reported per parameter: bias, relative bias, RMSE, empirical SD, mean SE,
# SE bias, and 95% CI coverage. Reported per sample size: convergence and
# admissibility rates, the Type I error rate of the scaled chi-square test,
# mean robust fit indices, and the spread of the TIF peak location.
# Criteria (Muthen & Muthen, 2002): |relative bias| <= 0.10,
# |SE bias| <= 0.10, and coverage between 0.91 and 0.98. Relative bias is not
# computed when |true value| < 0.2 (e.g., b2 ~ 0), where it is unstable.
#
# Scored parameters (all have an exact population value):
#   Phi      : 3 latent correlations (CFA, WLSMV, standardized solution)
#   a, b1-b3 : 36 x 4 GRM item parameters (per-domain unidimensional GRMs)
# CFA loadings are not scored: the data come from a logistic GRM, so the
# probit-metric loadings have no exact population value.
#
# Reproducibility: replication r of condition k uses
# set.seed(MC_SEED + 100000 * k + r), so results do not depend on the number
# of cores. Responses are drawn with a vectorized inverse-CDF step; the
# response model is identical to Section 1, only the random draws differ.
# =============================================================================

# --- Settings ----------------------------------------------------------------
# RUN_MC is deliberately NOT set to TRUE here. It defaults to FALSE so that
# sourcing this script reproduces the article in 1-3 minutes. To include the
# replication study, set RUN_MC <- TRUE in the console BEFORE sourcing (see
# the HOW TO RUN block at the top of this file); the line below preserves it.
if (!exists("RUN_MC")) RUN_MC <- FALSE
MC_REPS   <- 200L             # replications per sample size - DO NOT CHANGE
MC_N      <- c(1000L, 300L)   # 1,000 = this article; 300 = planned field study - DO NOT CHANGE
MC_SEED   <- SEED             # DO NOT CHANGE
MC_GRM_SE <- TRUE             # GRM standard errors (needed for coverage)
MC_CHUNK  <- 25L              # replications per progress report / checkpoint
MC_RESUME <- TRUE             # reuse MC_raw_results_N*.rds if settings match
MC_CORES  <- local({
  nc <- parallel::detectCores(logical = FALSE)
  if (is.na(nc)) nc <- parallel::detectCores()
  if (is.na(nc)) nc <- 1L
  max(1L, as.integer(nc) - 1L)
})

# --- True parameter table (fixed across replications) -----------------------
mc_pairs <- rbind(c("Cognitive", "Affective"),
                  c("Cognitive", "Conative"),
                  c("Affective", "Conative"))
mc_item_domain <- rep(domain_names, each = items_per_factor)
mc_true <- rbind(
  data.frame(Group  = "Phi",
             Domain = paste(mc_pairs[, 1], mc_pairs[, 2], sep = "-"),
             Param  = paste0("r(", substr(mc_pairs[, 1], 1, 3), ",",
                             substr(mc_pairs[, 2], 1, 3), ")"),
             True   = c(Phi[1, 2], Phi[1, 3], Phi[2, 3]),
             stringsAsFactors = FALSE),
  data.frame(Group  = "a",
             Domain = mc_item_domain,
             Param  = paste0("It", seq_len(n_items), "_a"),
             True   = a_params,
             stringsAsFactors = FALSE),
  data.frame(Group  = rep(c("b1", "b2", "b3"), each = n_items),
             Domain = rep(mc_item_domain, times = 3),
             Param  = paste0("It", rep(seq_len(n_items), times = 3), "_",
                             rep(c("b1", "b2", "b3"), each = n_items)),
             True   = as.vector(b_params),
             stringsAsFactors = FALSE)
)
n_par <- nrow(mc_true)   # 3 + 36 + 108 = 147; order: Phi, a, b1, b2, b3

# --- Data generation (same GRM as Section 1) --------------------------------
mc_generate <- function(n) {
  th  <- MASS::mvrnorm(n, mu = rep(0, n_factors), Sigma = Phi)
  out <- matrix(NA_integer_, n, n_items)
  for (i in seq_len(n_items)) {
    f    <- ((i - 1) %/% items_per_factor) + 1
    p_ge <- plogis(a_params[i] * outer(th[, f], b_params[i, ], "-"))  # P(X >= 2..4)
    u    <- runif(n)
    out[, i] <- 1L + as.integer(rowSums(u < p_ge))
  }
  out <- as.data.frame(out)
  names(out) <- paste0("It", seq_len(n_items))
  out
}

# --- CFA for one replication (same model and estimator as Section 2) --------
mc_fit_cfa <- function(d) {
  out <- list(converged = FALSE, admissible = FALSE,
              r = rep(NA_real_, 3), r_se = rep(NA_real_, 3),
              fit = c(ChiSq_p = NA_real_, CFI = NA_real_, TLI = NA_real_,
                      RMSEA = NA_real_, SRMR = NA_real_),
              error = "")
  fit <- tryCatch(
    suppressWarnings(lavaan::cfa(model_3F, data = d, estimator = "WLSMV",
                                 ordered = names(d))),
    error = function(e) e)
  if (inherits(fit, "error")) {
    out$error <- paste("CFA:", conditionMessage(fit))
    return(out)
  }
  out$converged <- isTRUE(lavaan::lavInspect(fit, "converged"))
  if (!out$converged) return(out)
  std_lambda <- lavaan::lavInspect(fit, "std")$lambda
  out$admissible <- !(any(diag(lavaan::lavInspect(fit, "cov.lv")) < 0) ||
                        any(abs(std_lambda[std_lambda != 0]) >= 1))
  ss <- lavaan::standardizedSolution(fit)
  for (j in seq_len(nrow(mc_pairs))) {
    hit <- ss$op == "~~" &
      ((ss$lhs == mc_pairs[j, 1] & ss$rhs == mc_pairs[j, 2]) |
         (ss$lhs == mc_pairs[j, 2] & ss$rhs == mc_pairs[j, 1]))
    if (sum(hit) == 1) {
      out$r[j]    <- ss$est.std[hit]
      out$r_se[j] <- ss$se[hit]
    }
  }
  fm <- lavaan::fitMeasures(fit)
  g  <- function(nm) if (nm %in% names(fm)) unname(as.numeric(fm[[nm]])) else NA_real_
  out$fit <- c(ChiSq_p = g("pvalue.scaled"),
               CFI     = g(paste0("cfi.", fit_sfx)),
               TLI     = g(paste0("tli.", fit_sfx)),
               RMSEA   = g(paste0("rmsea.", fit_sfx)),
               SRMR    = g("srmr"))
  out
}

# --- GRMs for one replication (same per-domain models as Section 3) ---------
mc_fit_grm <- function(d) {
  cols <- c("a", "b1", "b2", "b3")
  out  <- list(converged = FALSE, se_ok = FALSE,
               a = rep(NA_real_, n_items), a_se = rep(NA_real_, n_items),
               b = matrix(NA_real_, n_items, 3), b_se = matrix(NA_real_, n_items, 3),
               peak = setNames(rep(NA_real_, length(domain_names)), domain_names),
               error = "")
  # one row ("par" or "SE") of an item's coef() matrix, NA if unavailable
  get_row <- function(x, row) {
    if (!is.matrix(x) || !all(cols %in% colnames(x))) return(rep(NA_real_, 4))
    if (row %in% rownames(x)) return(as.numeric(x[row, cols]))
    if (row == "par") return(as.numeric(x[1, cols]))
    rep(NA_real_, 4)
  }
  conv  <- logical(length(domain_names))
  se_ok <- logical(length(domain_names))
  for (k in seq_along(domain_names)) {
    idx <- domain_idx[[k]]
    its <- names(d)[idx]
    m <- tryCatch(
      suppressWarnings(mirt::mirt(d[, idx], model = 1, itemtype = "graded",
                                  SE = MC_GRM_SE, verbose = FALSE)),
      error = function(e) e)
    if (inherits(m, "error")) {
      out$error <- paste0("GRM ", domain_names[k], ": ", conditionMessage(m))
      return(out)
    }
    conv[k] <- isTRUE(mirt::extract.mirt(m, "converged"))
    est_k <- NULL
    se_k  <- matrix(NA_real_, length(idx), 4)
    if (MC_GRM_SE) {
      # IRT-metric SEs via the delta method (rows "par" and "SE" per item)
      cs <- tryCatch(coef(m, IRTpars = TRUE, printSE = TRUE), error = function(e) NULL)
      est_k <- t(vapply(its, function(it) get_row(cs[[it]], "par"), numeric(4)))
      se_k  <- t(vapply(its, function(it) get_row(cs[[it]], "SE"),  numeric(4)))
      se_ok[k] <- isTRUE(mirt::extract.mirt(m, "secondordertest")) && all(is.finite(se_k))
    }
    if (is.null(est_k) || !all(is.finite(est_k))) {
      # same extraction as Section 3
      p     <- coef(m, IRTpars = TRUE, simplify = TRUE)$items
      est_k <- p[, cols, drop = FALSE]
    }
    out$a[idx]     <- est_k[, 1]
    out$b[idx, ]   <- est_k[, 2:4]
    out$a_se[idx]  <- se_k[, 1]
    out$b_se[idx, ] <- se_k[, 2:4]
    tif <- mirt::testinfo(m, theta_range)
    out$peak[k] <- theta_range[which.max(tif)]
  }
  out$converged <- all(conv)
  out$se_ok     <- all(se_ok)
  out
}

# --- One replication ---------------------------------------------------------
mc_one_rep <- function(r, n, cond) {
  seed_r <- MC_SEED + 100000L * as.integer(cond) + as.integer(r)
  set.seed(seed_r)
  t0 <- proc.time()[["elapsed"]]
  d  <- mc_generate(n)
  cats_ok <- all(vapply(d, function(x) length(unique(x)) == n_cats, logical(1)))
  est <- rep(NA_real_, n_par)
  se  <- rep(NA_real_, n_par)
  cfa <- NULL
  grm <- NULL
  if (cats_ok) {
    cfa <- mc_fit_cfa(d)
    grm <- mc_fit_grm(d)
    est <- c(cfa$r,    grm$a,    as.vector(grm$b))
    se  <- c(cfa$r_se, grm$a_se, as.vector(grm$b_se))
  }
  pick <- function(x, nm) if (is.null(x)) NA_real_ else unname(x[[nm]])
  errs <- c(if (!cats_ok) "empty response category", cfa$error, grm$error)
  info <- data.frame(
    N = n, Rep = r, Seed = seed_r, Cats_OK = cats_ok,
    CFA_Converged  = cats_ok && cfa$converged,
    CFA_Admissible = cats_ok && cfa$admissible,
    GRM_Converged  = cats_ok && grm$converged,
    GRM_SE_OK      = cats_ok && grm$se_ok,
    ChiSq_p = pick(cfa$fit, "ChiSq_p"),
    CFI     = pick(cfa$fit, "CFI"),
    TLI     = pick(cfa$fit, "TLI"),
    RMSEA   = pick(cfa$fit, "RMSEA"),
    SRMR    = pick(cfa$fit, "SRMR"),
    Peak_Cognitive = pick(grm$peak, "Cognitive"),
    Peak_Affective = pick(grm$peak, "Affective"),
    Peak_Conative  = pick(grm$peak, "Conative"),
    Seconds = proc.time()[["elapsed"]] - t0,
    Error   = paste(errs[nzchar(errs)], collapse = "; "),
    stringsAsFactors = FALSE
  )
  list(info = info, est = est, se = se)
}

# --- One sample-size condition, chunked with checkpoint/resume ---------------
mc_run_condition <- function(n, cond, cl = NULL) {
  ckpt <- sprintf("MC_raw_results_N%d.rds", n)
  st   <- list(reps = MC_REPS, n = n, cond = cond, seed = MC_SEED,
               grm_se = MC_GRM_SE, a = a_params, b = b_params, phi = Phi)
  res  <- vector("list", MC_REPS)
  if (MC_RESUME && file.exists(ckpt)) {
    old <- tryCatch(readRDS(ckpt), error = function(e) NULL)
    if (!is.null(old) && identical(old$settings, st)) {
      res <- old$results
      cat(sprintf("  [RESUME] N = %d: %d/%d replications loaded from %s\n",
                  n, sum(!vapply(res, is.null, logical(1))), MC_REPS, ckpt))
    } else {
      cat(sprintf("  [INFO] %s was made with other settings; N = %d restarts.\n", ckpt, n))
    }
  }
  todo <- which(vapply(res, is.null, logical(1)))
  t_start <- proc.time()[["elapsed"]]
  n_done_now <- 0L
  while (length(todo) > 0) {
    idx <- head(todo, MC_CHUNK)
    out <- if (is.null(cl)) {
      lapply(idx, mc_one_rep, n = n, cond = cond)
    } else {
      parallel::parLapplyLB(cl, idx, mc_one_rep, n = n, cond = cond)
    }
    res[idx] <- out
    saveRDS(list(settings = st, results = res), ckpt)
    todo <- setdiff(todo, idx)
    n_done_now <- n_done_now + length(idx)
    el <- proc.time()[["elapsed"]] - t_start
    cat(sprintf("  N = %4d | %3d/%d done | %5.1f min elapsed | ~%5.1f min left\n",
                n, MC_REPS - length(todo), MC_REPS, el / 60,
                el / n_done_now * length(todo) / 60))
  }
  res
}

# --- Summaries ---------------------------------------------------------------
mc_collect <- function(res) {
  list(info = do.call(rbind, lapply(res, `[[`, "info")),
       est  = do.call(rbind, lapply(res, `[[`, "est")),
       se   = do.call(rbind, lapply(res, `[[`, "se")))
}

mc_param_table <- function(cc, n) {
  z <- qnorm(0.975)
  rows <- lapply(seq_len(n_par), function(j) {
    ok <- if (mc_true$Group[j] == "Phi") cc$info$CFA_Admissible else cc$info$GRM_Converged
    e  <- cc$est[ok, j]
    s  <- cc$se[ok, j]
    keep <- is.finite(e)
    e  <- e[keep]
    s  <- s[keep]
    tv <- mc_true$True[j]
    if (length(e) < 2) {
      return(data.frame(Reps_Used = length(e), Mean_Est = NA_real_, Bias = NA_real_,
                        Rel_Bias = NA_real_, Emp_SD = NA_real_, RMSE = NA_real_,
                        Mean_SE = NA_real_, SE_Bias = NA_real_, Coverage_95 = NA_real_))
    }
    emp_sd  <- sd(e)
    s_ok    <- is.finite(s)
    mean_se <- if (any(s_ok)) mean(s[s_ok]) else NA_real_
    data.frame(Reps_Used   = length(e),
               Mean_Est    = mean(e),
               Bias        = mean(e) - tv,
               Rel_Bias    = if (abs(tv) >= 0.2) (mean(e) - tv) / tv else NA_real_,
               Emp_SD      = emp_sd,
               RMSE        = sqrt(mean((e - tv)^2)),
               Mean_SE     = mean_se,
               SE_Bias     = (mean_se - emp_sd) / emp_sd,
               Coverage_95 = if (any(s_ok)) mean(abs(e[s_ok] - tv) <= z * s[s_ok]) else NA_real_)
  })
  cbind(data.frame(N = n, mc_true, stringsAsFactors = FALSE), do.call(rbind, rows))
}

mc_group_table <- function(pt) {
  grp <- split(pt, list(pt$N, pt$Group, pt$Domain), drop = TRUE)
  agg <- do.call(rbind, lapply(grp, function(g) {
    rb <- g$Rel_Bias[is.finite(g$Rel_Bias)]
    data.frame(N = g$N[1], Group = g$Group[1], Domain = g$Domain[1],
               n_Params         = nrow(g),
               Reps_Used        = min(g$Reps_Used),
               Mean_Bias        = mean(g$Bias),
               Max_Abs_Rel_Bias = if (length(rb) > 0) max(abs(rb)) else NA_real_,
               Mean_RMSE        = mean(g$RMSE),
               Max_Abs_SE_Bias  = max(abs(g$SE_Bias)),
               Mean_Coverage    = mean(g$Coverage_95),
               Min_Coverage     = min(g$Coverage_95),
               Max_Coverage     = max(g$Coverage_95),
               stringsAsFactors = FALSE)
  }))
  agg$Criteria_Met <- (is.na(agg$Max_Abs_Rel_Bias) | agg$Max_Abs_Rel_Bias <= 0.10) &
    agg$Max_Abs_SE_Bias <= 0.10 & agg$Min_Coverage >= 0.91 & agg$Max_Coverage <= 0.98
  dom_order <- c(domain_names, unique(mc_true$Domain[mc_true$Group == "Phi"]))
  agg <- agg[order(-agg$N, match(agg$Group, c("Phi", "a", "b1", "b2", "b3")),
                   match(agg$Domain, dom_order)), ]
  rownames(agg) <- NULL
  agg
}

mc_fit_table <- function(info, n) {
  qq <- function(x, p) unname(stats::quantile(x, p, na.rm = TRUE))
  spread <- function(x) sprintf("%.2f [%.2f, %.2f]", mean(x, na.rm = TRUE),
                                qq(x, 0.025), qq(x, 0.975))
  ok  <- info$CFA_Admissible
  okg <- info$GRM_Converged
  data.frame(
    N                    = n,
    Replications         = nrow(info),
    With_Errors          = sum(nzchar(info$Error)),
    All_Categories_Used  = sum(info$Cats_OK),
    CFA_Converged        = sum(info$CFA_Converged),
    CFA_Admissible       = sum(ok),
    GRM_Converged        = sum(okg),
    GRM_SE_OK            = sum(info$GRM_SE_OK),
    Mean_CFI             = mean(info$CFI[ok], na.rm = TRUE),
    Mean_TLI             = mean(info$TLI[ok], na.rm = TRUE),
    Mean_RMSEA           = mean(info$RMSEA[ok], na.rm = TRUE),
    Mean_SRMR            = mean(info$SRMR[ok], na.rm = TRUE),
    ChiSq_Reject_Rate_05 = mean(info$ChiSq_p[ok] < 0.05, na.rm = TRUE),
    Peak_Theta_Cognitive = spread(info$Peak_Cognitive[okg]),
    Peak_Theta_Affective = spread(info$Peak_Affective[okg]),
    Peak_Theta_Conative  = spread(info$Peak_Conative[okg]),
    Mean_Seconds_per_Rep = mean(info$Seconds),
    stringsAsFactors = FALSE
  )
}

round_df <- function(df, digits = 3) {
  num <- vapply(df, is.double, logical(1))
  df[num] <- lapply(df[num], round, digits = digits)
  df
}

# --- Run ---------------------------------------------------------------------
if (RUN_MC) {
  cat("\n=== [MC] MONTE CARLO REPLICATION STUDY ===\n")
  cat(sprintf("  Settings: %d replications x N = %s | %d core(s) | GRM SEs: %s\n",
              MC_REPS, paste(MC_N, collapse = ", "), MC_CORES, MC_GRM_SE))

  # Pilot replication in this session: package or API problems stop the run
  # here, with a readable message, instead of failing silently in workers.
  pilot <- mc_one_rep(0L, n = MC_N[1], cond = 0L)
  if (nzchar(pilot$info$Error) || !pilot$info$CFA_Converged ||
      !pilot$info$GRM_Converged || !all(is.finite(pilot$est))) {
    stop("[FATAL] MC pilot replication failed: ",
         if (nzchar(pilot$info$Error)) pilot$info$Error else "non-convergence or missing estimates",
         call. = FALSE)
  }
  pilot_err <- pilot$est - mc_true$True
  cat(sprintf("  [OK] Pilot (N = %d, %.1f s): max |est - true| r = %.3f, a = %.3f, b = %.3f\n",
              MC_N[1], pilot$info$Seconds,
              max(abs(pilot_err[mc_true$Group == "Phi"])),
              max(abs(pilot_err[mc_true$Group == "a"])),
              max(abs(pilot_err[mc_true$Group %in% c("b1", "b2", "b3")]))))
  if (MC_GRM_SE && !pilot$info$GRM_SE_OK) {
    warning("[WARNING] GRM standard errors unavailable in the pilot; coverage may be NA.")
  }
  cat(sprintf("  [INFO] Upper-bound runtime estimate: ~%.0f min\n",
              pilot$info$Seconds * MC_REPS * length(MC_N) / MC_CORES / 60))

  cl <- NULL
  if (MC_CORES > 1L) {
    cl <- parallel::makeCluster(MC_CORES)
    invisible(parallel::clusterEvalQ(cl, {
      suppressPackageStartupMessages({
        library(lavaan)
        library(mirt)
      })
      NULL
    }))
    parallel::clusterExport(cl, envir = environment(), varlist = c(
      "mc_one_rep", "mc_generate", "mc_fit_cfa", "mc_fit_grm",
      "mc_true", "mc_pairs", "n_par", "a_params", "b_params", "Phi",
      "n_items", "n_cats", "n_factors", "items_per_factor",
      "domain_idx", "domain_names", "model_3F", "theta_range", "fit_sfx",
      "MC_SEED", "MC_GRM_SE"))
  }
  mc_results <- tryCatch(
    lapply(seq_along(MC_N), function(k) mc_run_condition(MC_N[k], cond = k, cl = cl)),
    finally = if (!is.null(cl)) parallel::stopCluster(cl)
  )

  mc_cc <- lapply(mc_results, mc_collect)
  mc_items <- do.call(rbind, lapply(seq_along(MC_N), function(k) {
    mc_param_table(mc_cc[[k]], MC_N[k])
  }))
  mc_groups <- mc_group_table(mc_items)
  mc_fit <- do.call(rbind, lapply(seq_along(MC_N), function(k) {
    mc_fit_table(mc_cc[[k]]$info, MC_N[k])
  }))

  mc_errors <- unlist(lapply(mc_cc, function(cc) cc$info$Error[nzchar(cc$info$Error)]))
  if (length(mc_errors) > 0) {
    cat(sprintf("  [WARNING] %d replication(s) reported errors. Most frequent:\n",
                length(mc_errors)))
    print(head(sort(table(mc_errors), decreasing = TRUE), 5))
  }

  cat("\n  Recovery summary (criteria: |rel. bias| & |SE bias| <= .10, coverage .91-.98):\n")
  print(round_df(mc_groups[, c("N", "Group", "Domain", "Mean_Bias", "Max_Abs_Rel_Bias",
                               "Mean_RMSE", "Mean_Coverage", "Criteria_Met")]),
        row.names = FALSE)
  cat("\n  Convergence and fit across replications:\n")
  print(t(round_df(mc_fit)))

  write_csv_utf8_bom(round_df(mc_groups), "ExtendedData_9_MC_Recovery_Summary.csv")

  # --- Table 6: recovery collapsed to parameter group (underlying data) -------
  # ExtendedData_9 reports recovery per (N, Group, Domain). Table 6 in the article
  # collapses that to (N, Group) by averaging across the three domains. The rows
  # written here are exactly the values printed in Table 6.
  mc_table6 <- function(gt) {
    grp <- split(gt, list(gt$N, gt$Group), drop = TRUE)
    out <- do.call(rbind, lapply(grp, function(g) {
      # Spaced column names (check.names = FALSE) so the printed table can wrap
      # its headers; underscored names are single unbreakable tokens in Word.
      data.frame(N = g$N[1], Group = g$Group[1],
                 `n Params`         = sum(g$n_Params),
                 `Mean Bias`        = mean(g$Mean_Bias),
                 `Max Abs Rel Bias` = if (all(is.na(g$Max_Abs_Rel_Bias))) NA_real_
                                      else max(g$Max_Abs_Rel_Bias, na.rm = TRUE),
                 `Mean RMSE`        = mean(g$Mean_RMSE),
                 `Mean Coverage`    = mean(g$Mean_Coverage),
                 `Min Coverage`     = min(g$Min_Coverage),
                 `Max Abs SE Bias`  = max(g$Max_Abs_SE_Bias),
                 # Plain integer 0-3, NOT "3/3": spreadsheet software silently
                 # converts fractions like 3/3 and 2/3 into dates on import.
                 `Domains Meeting Criteria` = as.integer(sum(g$Criteria_Met)),
                 stringsAsFactors = FALSE, check.names = FALSE)
    }))
    out <- out[order(-out$N, match(out$Group, c("Phi", "a", "b1", "b2", "b3"))), ]
    rownames(out) <- NULL
    out
  }
  mc_t6 <- mc_table6(mc_groups)
  write_csv_utf8_bom(round_df(mc_t6), "UnderlyingData_7_Table6_MC_Recovery_ByGroup.csv")

  write_csv_utf8_bom(round_df(mc_items),  "ExtendedData_10_MC_Item_Level_Recovery.csv")
  write_csv_utf8_bom(round_df(mc_fit),    "ExtendedData_11_MC_Convergence_Fit.csv")
} else {
  cat("\n=== [MC] Monte Carlo replication study skipped (RUN_MC = FALSE) ===\n")
}


# =============================================================================
# SECTION 7: FINAL COMPLIANCE VERIFICATION
# =============================================================================
cat("\n", paste(rep("=", 70), collapse = ""), "\n", sep = "")
cat("FINAL COMPLIANCE VERIFICATION (F1000Research Standards)\n")
cat(paste(rep("=", 70), collapse = ""), "\n", sep = "")

cat("\n[FIGURE VERIFICATION]\n")
if (nrow(.fig_manifest) == 0) {
  cat("  [WARNING] No figures recorded in the manifest.\n")
} else {
  for (i in seq_len(nrow(.fig_manifest))) {
    row         <- .fig_manifest[i, ]
    file_exists <- file.exists(row$File)
    size_mb     <- if (file_exists) file.info(row$File)$size / 1024 / 1024 else NA_real_
    width_ok    <- row$Width_mm >= (FIG_WIDTH_MM_MIN - 0.5) &
      row$Width_mm <= (FIG_WIDTH_MM_MAX + 0.5)
    dpi_ok      <- row$DPI >= FIG_DPI_MIN
    status      <- if (file_exists && width_ok && dpi_ok) "[OK]" else "[WARNING]"
    cat(sprintf("  %s %s: %.0f x %.0f mm | %d dpi | %s\n",
                status, row$File, row$Width_mm, row$Height_mm, row$DPI,
                if (file_exists) sprintf("%.2f MB", size_mb) else "FILE NOT FOUND"))
    if (!width_ok) {
      cat(sprintf("      -> width %.0f mm is outside the %d-%d mm guideline range.\n",
                  row$Width_mm, FIG_WIDTH_MM_MIN, FIG_WIDTH_MM_MAX))
    }
  }
}

csv_files <- list.files(pattern = "\\.csv$")
cat(sprintf("\n[TABLES/DATA] %d CSV files generated.\n", length(csv_files)))

all_files <- list.files(pattern = "\\.(tiff|csv)$")
sizes_mb  <- file.info(all_files)$size / 1024 / 1024
if (any(sizes_mb > 10, na.rm = TRUE)) {
  cat("\n[INFO] Some TIFF files exceed 10 MB (heuristic, not a guideline value):\n")
  print(data.frame(File = all_files[sizes_mb > 10],
                   Size_MB = round(sizes_mb[sizes_mb > 10], 2)))
  # FIG_COMPRESSION defaults to "none"; "lzw" is the lossless fallback
  cat("   If the submission portal rejects this size, set FIG_COMPRESSION <- \"lzw\" (lossless) in Section 0.\n")
} else {
  cat("\n[OK] All files are under 10 MB (heuristic).\n")
}

cat(sprintf("\n[TOTAL] %d files generated.\n", length(all_files)))
cat("   - Main Article: 5 Figures + 5 Tables (Underlying Data)\n")
cat(sprintf("   - Supplementary: 3 Figures + %d Tables (Extended Data)\n",
            if (isTRUE(RUN_MC)) 7L else 4L))
if (isTRUE(RUN_MC)) {
  cat(sprintf("   - Monte Carlo: %d replications x N = %s (Extended Data 9-11)\n",
              MC_REPS, paste(MC_N, collapse = "/")))
}

cat("\n", paste(rep("=", 70), collapse = ""), "\n", sep = "")
cat("SCRIPT COMPLETE — READY FOR SUBMISSION\n")
cat(sprintf("   - Figures: %d-%d mm width (1-2 columns), %d dpi, TIFF\n",
            FIG_WIDTH_MM_MIN, FIG_WIDTH_MM_MAX, FIG_DPI_MIN))
cat("   - Line art text: >= 8 pt in all figures\n")
cat("   - Tables: CSV with UTF-8 BOM (symbols preserved in Excel)\n")
cat("   - Fonts: sans-serif, consistent across all figures\n")
cat("   - Order: narrative sequence (Sec 3 -> 4.1 -> 4.2 -> 4.3 -> 5.3)\n")
cat("   - Formatting: summary tables to 3 decimals (chi-square 2); scaled WLSMV p-value\n")
cat("   - GRM and reliability: calibrated per domain (Cognitive/Affective/Conative)\n")
cat("   - Typology logic: 'Conative-Deficit' requires Conative = argmin\n")
cat("   - Fig 1 detail text: auto word-wrapped, never clipped\n")
cat(paste(rep("=", 70), collapse = ""), "\n", sep = "")

cat("\n[REPRODUCIBILITY] Session info:\n")
print(sessionInfo())